version: '3'
services:
  floodapi:
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - ./backend/:/app 
    ports:
     - "5000:5000"
    environment:
     - DARK_SKY_API_KEY=ac49424582fd2f061dd0f3ac9fe66076

  frontend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - '3500:80'
    environment:
     - REACT_APP_GOOGLE_API_KEY=AIzaSyC2qcWx-Xcjy3KPjNs2mUHrsQ2HP9fXwWM
     - REACT_APP_EZW_API=http://0.0.0.0:5000/api/floodapi